version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:17'
      timezone: Europe/Berlin
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /ovk
    schedule:
      interval: weekly
      day: monday
      time: '06:37'
      timezone: Europe/Berlin
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
