// @ts-check
// `@type` JSDoc annotations allow editor autocompletion and type checking
// (when paired with `@ts-check`).
// There are various equivalent ways to declare your Docusaurus config.
// See: https://docusaurus.io/docs/api/docusaurus-config

import { themes as prismThemes } from 'prism-react-renderer';

import {
  collectWerbeformenMenu,
  collectWerbeformenRedirects,
} from './scripts/werbeformen-routes.mjs';

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'OVK Tech Specs',
  tagline: 'Technische Standards des Online-Vermarkterkreises',
  favicon: 'img/logo_ovk_mobile.png',

  url: 'https://tech.ovk.de',
  baseUrl: '/',
  trailingSlash: false,

  future: {
    v4: {
      removeLegacyPostBuildHeadAttribute: true,
      // Keep the pre-v4 CSS cascade: with layers on, the global rules in
      // src/css/custom.css (e.g. `a { color: ... }`) would override the
      // theme's component colors for menus, sidebars, and breadcrumbs.
      useCssCascadeLayers: false,
      siteStorageNamespacing: true,
      fasterByDefault: true,
      mdx1CompatDisabledByDefault: true,
    },
    faster: true,
  },

  organizationName: 'BVDW-org',
  projectName: 'ovk-docusaurus',

  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',
  markdown: {
    hooks: {
      onBrokenMarkdownImages: 'throw',
      onBrokenMarkdownLinks: 'throw',
    },
    // The v4 future flag disables MDX v1 compat by default. Explicit heading
    // anchors like `### Criteo {#Criteo}` are used by the synchronized
    // identity documentation (and generated by normalize-synced-content.mjs),
    // so that one compat feature must stay on.
    mdx1Compat: {
      headingIds: true,
    },
  },

  clientModules: [require.resolve('./src/clientModules/identitySolutionsEnhancer.js')],

  i18n: {
    defaultLocale: 'de',
    locales: ['de'],
    localeConfigs: {
      de: {
        htmlLang: 'de-DE',
        label: 'Deutsch',
      },
    },
  },

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          // Synchronized sections must be edited in their upstream source
          // repositories, so only documentation that is maintained in this
          // repository gets an edit link.
          editUrl: ({ docPath }) =>
            docPath.startsWith('tools/')
              ? `https://github.com/BVDW-org/ovk-docusaurus/edit/main/ovk/docs/${docPath}`
              : undefined,
        },
        blog: false,
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],

  plugins: [
    [
      '@docusaurus/plugin-pwa',
      {
        offlineModeActivationStrategies: [
          'appInstalled',
          'standalone',
          'queryString',
        ],
        pwaHead: [
          {
            tagName: 'link',
            rel: 'manifest',
            href: '/manifest.json',
          },
          {
            tagName: 'link',
            rel: 'apple-touch-icon',
            href: '/img/pwa/apple-touch-icon.png',
          },
          {
            tagName: 'meta',
            name: 'theme-color',
            content: '#010f2d',
          },
          {
            tagName: 'meta',
            name: 'apple-mobile-web-app-capable',
            content: 'yes',
          },
          {
            tagName: 'meta',
            name: 'apple-mobile-web-app-status-bar-style',
            content: 'default',
          },
          {
            tagName: 'meta',
            name: 'apple-mobile-web-app-title',
            content: 'OVK Tech Specs',
          },
        ],
      },
    ],
    [
      '@docusaurus/plugin-client-redirects',
      {
        // Legacy Werbeformen routes (spaces, umlauts, "Werbeformen_new")
        // redirect to the stable ASCII slugs injected during content sync.
        redirects: collectWerbeformenRedirects(),
      },
    ],
  ],

  themes: [
    [
      require.resolve('@easyops-cn/docusaurus-search-local'),
      /** @type {import('@easyops-cn/docusaurus-search-local').PluginOptions} */
      ({
        hashed: true,
        language: ['en', 'de'],
        indexBlog: false,
      }),
    ],
  ],

  themeConfig:
  /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
      ({
        image: 'img/ovk-hero-technical-grid.png',
        metadata: [
          {
            name: 'keywords',
            content:
              'OVK, Tech Specs, Identity, Contextual Standard, Werbeformen, digitale Werbung',
          },
        ],
        colorMode: {
          defaultMode: 'light',
          disableSwitch: false,
          respectPrefersColorScheme: true,
        },
        navbar: {
          title: 'Tech Specs',
          logo: {
            alt: 'OVK Logo',
            src: 'img/logo_ovk_mobile.png',
          },
          items: [
            {
              type: 'dropdown',
              to: '/docs/identitysolutions/',
              label: 'Identity',
              position: 'left',
              items: [
                { type: 'doc', docId: 'identitysolutions/README', label: 'Einführung' },
                { type: 'doc', docId: 'identitysolutions/Case Studies', label: 'Case Studies' },
                {
                  type: 'doc',
                  docId: 'identitysolutions/ID-Support_OVK-Vermarkter/OVK-IdentifierSupport_byVendor',
                  label: 'Vermarkter ID-Übersicht',
                },
                { type: 'doc', docId: 'tools/id-landscape-map', label: 'ID Landscape Map' },
              ],
            },
            { to: '/docs/contextualstandards/', label: 'OVK Contextual Standard', position: 'left' },
            {
              // Two-level dropdown rendered by src/components/NestedDropdownNavbarItem.
              // The nested tree is derived from the synced Werbeformen files,
              // so upstream additions appear automatically after a sync.
              type: 'custom-nestedDropdown',
              to: '/docs/werbeformen',
              label: 'Werbeformen',
              position: 'left',
              items: collectWerbeformenMenu(),
            },
          ],
        },
        footer: {
          style: 'light',
          links: [{
            title: 'Menü',
            items: [
              {
                label: 'Der OVK',
                href: 'https://www.ovk.de/der-ovk/',
              },
              {
                label: 'Projekte',
                href: 'https://www.ovk.de/projekte/',
              },
              {
                label: 'News',
                href: 'https://www.ovk.de/news/',
              },
              {
                label: 'Kontakt',
                href: 'https://www.ovk.de/kontakt/',
              },
            ],
          },
            
            {
              title: 'Folgen Sie uns',
              items: [
                {
                  label: 'LinkedIn',
                  href: 'https://www.linkedin.com/company/german-federal-association-of-the-digital-economy-bvdw-e.v.-/',
                },
                {
                  label: 'Xing',
                  href: 'https://www.xing.com/companies/bundesverbanddigitalewirtschaft',
                },
                {
                  label: 'Facebook',
                  href: 'https://www.facebook.com/BVDW.eV',
                },
              ],
            },
            {
              title: 'Weiteres',
              items: [
                {
                  label: 'Impressum',
                  href: 'https://www.ovk.de/impressum/',
                },
                {
                  label: 'Datenschutz',
                  href: 'https://www.ovk.de/datenschutz/',
                },
                {
                  label: 'Downloads',
                  href: 'https://www.ovk.de/downloads/',
                },
              ],
            },
          ],
         
          copyright: `Copyright © ${new Date().getFullYear()} Online-Vermarkterkreis (OVK).`,
        },
        prism: {
          theme: prismThemes.github,
          darkTheme: prismThemes.dracula,
        },
      }),
};


export default config;
