// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Manually create a sidebar
  tutorialSidebar: [
   
    {
      type: 'category',
      label: 'Identity',
      items: [
        {
          type: 'autogenerated',
          dirName: 'identitysolutions',
        },
      ],
    },
    {
      type: 'category',
      label: 'OVK Contextual Standard',
      items: [
        {
          type: 'autogenerated',
          dirName: 'contextualstandards',
        },

      ],
    }
  ],
};

export default sidebars;