// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Manually create a sidebar
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Identity',
      items: [
        { type: 'doc', id: 'identitysolutions/README' },
        { type: 'doc', id: 'identitysolutions/Case Studies' },
        { type: 'doc', id: 'identitysolutions/ID-Support_OVK-Vermarkter/OVK-IdentifierSupport' },
        { type: 'doc', id: 'identitysolutions/ID-Support_OVK-Vermarkter/OVK-IdentifierSupport_byVendor' },
        
        // Füge nur die gewünschten Dateien hinzu, die du anzeigen willst
      ],
    },
    {
      type: 'category',
      label: 'OVK Contextual Standard',
      items: [
        {
          type: 'autogenerated',
          dirName: 'contextualstandards',
        },
      ],
    }
  ],
};

export default sidebars;
