// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Manually create a sidebar
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Identity Solutions',
      items: [
        {
          type: 'autogenerated',
          dirName: 'identitysolutions',
        },
      ],
    },
    {
      type: 'category',
      label: 'Contextual Standards',
      items: [
        {
          type: 'autogenerated',
          dirName: 'contextualstandards',
        },

      ],
    },
    {
      type: 'category',
      label: 'Werbeformen',
      items: [
        {
          type: 'autogenerated',
          dirName: 'werbeformen',
        },

      ],
    },
  ],
};

export default sidebars;