name: Sync identitysolutions

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Läuft einmal täglich um Mitternacht

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ovk-docusaurus
      uses: actions/checkout@v2
      with:
        repository: BVDW-org/ovk-docusaurus
        path: ovk-docusaurus

    - name: Checkout ovk-identifiersupport
      uses: actions/checkout@v2
      with:
        repository: BVDW-org/ovk-identifiersupport
        path: ovk-identifiersupport
        token: ${{ secrets.GH_TOKEN }}
        ref: main  # Explizit den Branch 'main' angeben

    - name: List all files in ovk-identifiersupport
      run: ls -R ovk-identifiersupport

    - name: List files in ovk-docusaurus before copy
      run: ls -la ovk-docusaurus/ovk/docs

    - name: List files in ovk-identifiersupport before copy
      run: ls -la ovk-identifiersupport/ovk/docs/identitysolutions

    - name: Copy identitysolutions to ovk-docusaurus
      run: |
        echo "Removing old identitysolutions folder if it exists"
        rm -rf ovk-docusaurus/ovk/docs/identitysolutions
        echo "Copying identitysolutions folder"
        cp -r ovk-identifiersupport/ovk/docs/identitysolutions ovk-docusaurus/ovk/docs/
        echo "Files after copy:"
        ls -la ovk-docusaurus/ovk/docs/identitysolutions

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd ovk-docusaurus
        git config --global user.email "your-email@example.com"
        git config --global user.name "github-actions[bot]"
        git add ovk/docs/identitysolutions
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m "Update identitysolutions from ovk-identifiersupport"
          git push origin main
        fi
