name: Sync identitysolutions

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (fixed cron syntax)
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout ovk-docusaurus
      uses: actions/checkout@v4  # Updated to latest version
      with:
        repository: BVDW-org/ovk-docusaurus
        path: ovk-docusaurus
        fetch-depth: 1  # Shallow clone for better performance
    
    - name: Checkout ovk-identifiersupport
      uses: actions/checkout@v4  # Updated to latest version
      with:
        repository: BVDW-org/ovk-identifiersupport
        path: ovk-identifiersupport
        token: ${{ secrets.GH_TOKEN }}
        ref: main
        fetch-depth: 1  # Shallow clone for better performance
    
    - name: Validate repositories
      run: |
        if [ ! -d "ovk-identifiersupport" ]; then
          echo "::error::Source repository (ovk-identifiersupport) not properly checked out"
          exit 1
        fi
        
        if [ ! -d "ovk-docusaurus" ]; then
          echo "::error::Target repository (ovk-docusaurus) not properly checked out"
          exit 1
        fi
    
    - name: Sync identitysolutions folder
      run: |
        echo "Creating backup of current identitysolutions folder"
        mkdir -p backup
        if [ -d "ovk-docusaurus/ovk/docs/identitysolutions" ]; then
          cp -r ovk-docusaurus/ovk/docs/identitysolutions backup/
        fi
        
        echo "Removing old identitysolutions folder"
        rm -rf ovk-docusaurus/ovk/docs/identitysolutions
        mkdir -p ovk-docusaurus/ovk/docs/identitysolutions
        
        echo "Copying identitysolutions files"
        cp -r ovk-identifiersupport/* ovk-docusaurus/ovk/docs/identitysolutions/
        
        echo "Verification: Files after copy:"
        ls -la ovk-docusaurus/ovk/docs/identitysolutions
    
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd ovk-docusaurus
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # Add changes
        git add ovk/docs/identitysolutions
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes detected in the content - skipping commit"
        else
          # Commit and push changes
          git commit -m "Update identitysolutions from ovk-identifiersupport [automated sync]"
          git push origin main || {
            echo "::error::Failed to push changes. Attempting to restore from backup..."
            if [ -d "../backup/identitysolutions" ]; then
              rm -rf ovk/docs/identitysolutions
              cp -r ../backup/identitysolutions ovk/docs/
              echo "Restored from backup."
            fi
            exit 1
          }
          echo "Successfully updated identitysolutions content"
        fi
