name: Sync werbeformen docs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (fixed cron syntax)
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ovk-docusaurus
      uses: actions/checkout@v4  # Updated to latest version
      with:
        repository: BVDW-org/ovk-docusaurus
        path: ovk-docusaurus
        fetch-depth: 1  # Shallow clone for better performance
    
    - name: Checkout ovk-werbeformen
      uses: actions/checkout@v4  # Updated to latest version
      with:
        repository: BVDW-org/ovk-werbeformen
        path: ovk-werbeformen
        token: ${{ secrets.GH_TOKEN }}
        ref: main
        fetch-depth: 1  # Shallow clone for better performance
    
    - name: Validate repositories
      run: |
        if [ ! -d "ovk-werbeformen/werbeformen.org/docs" ]; then
          echo "::error::Source directory (ovk-werbeformen/werbeformen.org/docs) not properly checked out or doesn't exist"
          exit 1
        fi
        
        if [ ! -d "ovk-docusaurus" ]; then
          echo "::error::Target repository (ovk-docusaurus) not properly checked out"
          exit 1
        fi
    
    - name: List source files
      run: ls -R ovk-werbeformen/werbeformen.org/docs
    
    - name: Create backup of existing werbeformen docs
      run: |
        if [ -d "ovk-docusaurus/ovk/docs/werbeformen" ]; then
          echo "Creating backup of current werbeformen folder"
          mkdir -p backup
          cp -r ovk-docusaurus/ovk/docs/werbeformen backup/
        fi
    
    - name: Sync werbeformen folder
      run: |
        echo "Removing old werbeformen folder"
        rm -rf ovk-docusaurus/ovk/docs/werbeformen
        mkdir -p ovk-docusaurus/ovk/docs/werbeformen
        
        echo "Copying werbeformen docs"
        cp -r ovk-werbeformen/werbeformen.org/docs/* ovk-docusaurus/ovk/docs/werbeformen/
        
        echo "Verification: Files after copy:"
        ls -la ovk-docusaurus/ovk/docs/werbeformen
    
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd ovk-docusaurus
        git config --global user.email "carlos.bracho@axelspringer.com"
        git config --global user.name "github-actions[bot]"
        
        # Add changes
        git add ovk/docs/werbeformen
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes detected in the content - skipping commit"
        else
          # Commit and push changes
          git commit -m "Update werbeformen docs from ovk-werbeformen"
          git push origin main || {
            echo "::error::Failed to push changes. Attempting to restore from backup..."
            if [ -d "../backup/werbeformen" ]; then
              rm -rf ovk/docs/werbeformen
              cp -r ../backup/werbeformen ovk/docs/
              echo "Restored from backup."
            fi
            exit 1
          }
          echo "Successfully updated werbeformen docs"
        fi
